//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mBankWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public Customer()
        {
            this.Transaction_details = new HashSet<Transaction_details>();
        }
    
        public int ID { get; set; }
        public string ExternalCustomerId { get; set; }
        public string Name { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string ContactNumber1 { get; set; }
        public string ContactNumber2 { get; set; }
        public Nullable<int> RoleId { get; set; }
        public Nullable<int> AgentId { get; set; }
        public Nullable<int> BankId { get; set; }
        public string CustomerPhoto { get; set; }
        public Nullable<bool> Gender { get; set; }
        public string PancardNumber { get; set; }
        public string EmailId { get; set; }
        public Nullable<bool> IsSyncronise { get; set; }
        public Nullable<System.DateTime> BankSyncroniseDate { get; set; }
        public Nullable<System.DateTime> SyncroniseDate { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public Nullable<bool> Deleted { get; set; }
    
        public virtual Agent Agent { get; set; }
        public virtual Bank Bank { get; set; }
        public virtual UsersRole UsersRole { get; set; }
        public virtual ICollection<Transaction_details> Transaction_details { get; set; }
    }
}
