//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mBankWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.Accounts = new HashSet<Account>();
            this.Transaction_details = new HashSet<Transaction_details>();
        }
    
        public int ID { get; set; }
        public string ProductName { get; set; }
        public string ProductDetails { get; set; }
        public string ShortName { get; set; }
        public Nullable<int> BankId { get; set; }
        public Nullable<int> BranchId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<bool> Deleted { get; set; }
    
        public virtual ICollection<Account> Accounts { get; set; }
        public virtual Bank Bank { get; set; }
        public virtual Branch Branch { get; set; }
        public virtual ICollection<Transaction_details> Transaction_details { get; set; }
    }
}
