//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mBankWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SuperAdmin
    {
        public SuperAdmin()
        {
            this.Banks = new HashSet<Bank>();
        }
    
        public int ID { get; set; }
        public string SuperAdminName { get; set; }
        public string Password { get; set; }
    
        public virtual ICollection<Bank> Banks { get; set; }
    }
}
