//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mBankWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction_details
    {
        public int ID { get; set; }
        public string ExternalTransactionId { get; set; }
        public Nullable<int> BankId { get; set; }
        public Nullable<int> BranchId { get; set; }
        public Nullable<int> ManagerId { get; set; }
        public Nullable<int> AgentId { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<int> AccountId { get; set; }
        public Nullable<double> Amount { get; set; }
        public Nullable<double> InterestAmount { get; set; }
        public Nullable<double> BalanceAmount { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
        public Nullable<int> ProducttypeId { get; set; }
        public Nullable<bool> deleted { get; set; }
        public Nullable<int> NumberofDays { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<bool> IsSyncronise { get; set; }
        public Nullable<System.DateTime> BankSyncroniseDate { get; set; }
        public Nullable<System.DateTime> SyncroniseDate { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Agent Agent { get; set; }
        public virtual Bank Bank { get; set; }
        public virtual Branch Branch { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual Manager Manager { get; set; }
        public virtual Product Product { get; set; }
    }
}
