//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mBankWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsersRole
    {
        public UsersRole()
        {
            this.Admins = new HashSet<Admin>();
            this.Agents = new HashSet<Agent>();
            this.Customers = new HashSet<Customer>();
            this.UserDetails = new HashSet<UserDetail>();
        }
    
        public int ID { get; set; }
        public string RollName { get; set; }
        public Nullable<bool> IsSyncronise { get; set; }
        public Nullable<System.DateTime> SyncroniseDate { get; set; }
        public Nullable<System.DateTime> BanksyncroniseDate { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public Nullable<bool> Deleted { get; set; }
    
        public virtual ICollection<Admin> Admins { get; set; }
        public virtual ICollection<Agent> Agents { get; set; }
        public virtual ICollection<Customer> Customers { get; set; }
        public virtual ICollection<UserDetail> UserDetails { get; set; }
    }
}
