//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mBankWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserDetail
    {
        public int ID { get; set; }
        public Nullable<int> RoleId { get; set; }
        public Nullable<int> BankId { get; set; }
        public Nullable<int> BranchId { get; set; }
        public string Password { get; set; }
        public string ConfirmPassword { get; set; }
        public Nullable<bool> IsSyncronise { get; set; }
        public Nullable<System.DateTime> SyncroniseDate { get; set; }
        public Nullable<System.DateTime> BankSyncroniseDate { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public Nullable<bool> Deleted { get; set; }
    
        public virtual Bank Bank { get; set; }
        public virtual Branch Branch { get; set; }
        public virtual UsersRole UsersRole { get; set; }
    }
}
